# Generated by Django 2.2.3 on 2019-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190725_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
