# Generated by Django 2.2.3 on 2019-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_discription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
