# Generated by Django 2.2.3 on 2019-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_user_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
